apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "cpchart.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "cpchart.name" . }}
    chart: {{ template "cpchart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "cpchart.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "cpchart.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - name: config-files
          mountPath: /go/bin/config
      serviceAccountName: "admin-user"
      serviceAccount: "admin-user"
      volumes: 
      - name: config-files
        configMap:
          name: {{ template "cpchart.fullname" . }}
          
